name: Substitute Placeholder Values
description: Substitutes placeholder values
branding:
  icon: file-text
  color: blue
inputs:
  target:
    description: Target file or directory
    required: true
  values:
    description: Substitute values in JSON format
    required: true
  keyword:
    description: Keyword
    required: true
    default: config
runs:
  using: composite
  steps:
    - shell: bash
      env:
        TARGET: ${{ inputs.target }}
        VALUES: ${{ inputs.values }}
        KEYWORD: ${{ inputs.keyword }}
      run: |
        substitute_placeholders_in_target () {
          cd "$1"
          for item in *; do
            substitute_placeholders_in_name "$item"
            substitute_placeholders_in_content "$item"        
          done
          cd ..
        }
          
        substitute_placeholders_in_name () {
          item="$1"
          item_substitute_name=$(substitute_placeholders "$item")
          if [ "$item" != "$item_substitute_name" ]; then
            mv "$item" "$item_substitute_name"
            item=$item_substitute_name
          fi
        }

        substitute_placeholders_in_content () {
          item="$1"
          if [[ -d $item ]]; then
            [ "$(ls -A "$item")" ] && apply_config "$item"
          else
            substitute_placeholders "$(cat $item)" > $item
          fi
        }
          
        substitute_placeholders () {
          str="$1"
          keys=$(echo "$VALUES" | jq -r '. | keys[]')
          for key in $keys; do
            value=$(echo "$VALUES" | jq -r ".$key")
            str=$(echo "$str" | sed "s/{{\s*$KEYWORD.$key\s*}}/$value/g")
          done
          echo "$str"
        }
          
        substitute_placeholders_in_target "$TARGET"
