name: Insert Variables
description: Inserts Variables
branding:
  icon: file-text
  color: blue
inputs:
  target:
    description: Target file or directory
    required: true
  context:
    description: Context
    required: true
  values:
    description: Values in JSON format
    required: true
runs:
  using: composite
  steps:        

    - shell: bash
      env:
        TARGET: ${{ inputs.target }}
        CONTEXT: ${{ inputs.context }}
        VALUES: ${{ inputs.values }}
      run: |
        create_insertion_expression() {
          local keys=$(echo "$VALUES" | jq keys)
          local cmds='[]'
          local key value_escaped cmd
          for (( i=0; i<$(echo "$keys" | jq length); i++ )); do
            key=$(echo "$keys" | jq -r --argjson i $i '.[$i]')
            # See https://stackoverflow.com/a/29613573
            IFS= read -d '' -r < <(
              echo "$VALUES" \
              | jq -r --arg key "$key" '.[$key]' \
              | sed -e ':a' -e '$!{N;ba' -e '}' -e 's/[&/\]/\\&/g; s/\n/\\&/g'
            )
            value_escaped=${REPLY%$'\n'}
            cmd="s/{{\s*$CONTEXT.$key\s*}}/$value_escaped/g"
            cmds=$(echo "$cmds" | jq --arg cmd "$cmd" '. += [$cmd]')
          done
          echo "$cmds" | jq -r 'join("; ")'
        }

        insert_variables () {
          local name substitute_name
          for item in "$1"/*; do
            [ -d "$item" ] && \
              [ -z "$(ls -A "$item")" ] && insert_variables "$item" \
            || \
              sed -i "$insertion_expression" "$item"
            name=$(basename "$item")
            substitute_name=$(echo "$name" | sed "$insertion_expression")
            [ "$substitute_name" != "$name" ] && mv "$item" "$1/$substitute_name"
          done
        }
        
        insertion_expression=$(create_insertion_expression)
        insert_variables "$TARGET"
