name: Substitute Placeholder Values
description: Substitutes placeholder values
branding:
  icon: file-text
  color: blue
inputs:
  target:
    description: Target file or directory
    required: true
  values:
    description: Substitute values in JSON format
    required: true
  keyword:
    description: Keyword
    required: true
    default: config
runs:
  using: composite
  steps:
    - shell: bash
      env:
        TARGET: ${{ inputs.target }}
        VALUES: ${{ inputs.values }}
        KEYWORD: ${{ inputs.keyword }}
      run: |
        substitute_placeholders_in_dir () {
          cd "$1"
          for item in *; do
            substitute_placeholders_in_content "$item"        
            substitute_placeholders_in_name "$item"
          done
          cd -
        }
          
        substitute_placeholders_in_name () {
          local name="$1"
          local substitute_name=$(substitute_placeholders_in_string "$item")
          if [ "$name" != "$substitute_name" ]; then
            mv "$name" "$substitute_name"
          fi
        }

        substitute_placeholders_in_content () {
          local item="$1"
          if [[ -d $item ]]; then
            [ "$(ls -A "$item")" ] && substitute_placeholders_in_dir "$item"
          else
            substitute_placeholders_in_string "$(cat $item)" > $item
          fi
        }
          
        substitute_placeholders_in_string () {
          local str="$1"
          local keys=$(echo "$VALUES" | jq -r '. | keys[]')
          local value
          for key in $keys; do
            value=$(echo "$VALUES" | jq -r ".$key")
            str=$(echo "$str" | sed "s/{{\s*$KEYWORD.$key\s*}}/$value/g")
          done
          echo "$str"
        }
          
        substitute_placeholders_in_dir "$TARGET"
