name: Insert Variables
description: Inserts Variables
branding:
  icon: file-text
  color: blue
inputs:
  target:
    description: Target file or directory
    required: true
  context:
    description: Context
    required: true
  values:
    description: Values in JSON format
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      env:
        TARGET: ${{ inputs.target }}
        CONTEXT: ${{ inputs.context }}
        VALUES: ${{ inputs.values }}
      run: |
        insert_variables_in_dir () {
          cd "$1"
          for item in *; do
            insert_variables_in_content "$item"        
            insert_variables_in_name "$item"
          done
          cd -
        }
          
        insert_variables_in_name () {
          local name="$1"
          local substitute_name=$(insert_variables_in_string "$item")
          if [ "$name" != "$substitute_name" ]; then
            mv "$name" "$substitute_name"
          fi
        }

        insert_variables_in_content () {
          local item="$1"
          if [[ -d $item ]]; then
            [ "$(ls -A "$item")" ] && insert_variables_in_dir "$item"
          else
            insert_variables_in_string "$(cat $item)" > $item
          fi
        }
          
        insert_variables_in_string () {
          local str="$1"
          local keys=$(echo "$VALUES" | jq keys)
          local key
          local value_escaped
          for (( i=0; i<$(echo "$keys" | jq length); i++ )); do
            key=$(echo "$keys" | jq -r --argjson i $i '.[$i]')
            # See https://stackoverflow.com/a/29613573
            value_escaped=$(
                echo "$VALUES" \
                | jq -r --arg key "$key" '.[$key]' \
                | sed -e ':a' -e '$!{N;ba' -e '}' -e 's/[&/\]/\\&/g; s/\n/\\&/g'
            )
            str=$(echo "$str" | sed "s/{{\s*$CONTEXT.$key\s*}}/$value_escaped/g")
          done
          echo "$str"
        }
          
        insert_variables_in_dir "$TARGET"
