name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Action
        uses: ./
        with:
          target: .
          contexts: |
            [
              {
                "name": test,
                "values": {
                  "foo": "bar"
                }
              }
            ]
